language: go
go_import_path: github.com/CiscoCloud/mesos-consul
go:
- 1.8
script: go test -v $(go list ./... | grep -v vendor)
before_deploy:
- go get github.com/mitchellh/gox
- gox -output="build/{{.Dir}}_{{.OS}}_{{.Arch}}"
deploy:
  provider: releases
  api_key:
    secure: tSI0CLteEAhwGfJOazyDIK/H85JrYEKh1K577RS3Be8lSS/QMvl2Rn0LuIgn/6YG55Jt2KbXrwlRuhe0scB4VXM/QrHBCNo5SiaYcy7MfGqRFS3QjENYRPyocxXRZTYFCzH8bHAYsydR00TZtonfEWv/BLReF3JwTnBUXuleaVbCmLWVGtYOCBCcSGil6CIDMENt8rh6n6zAFvqPTC3MuvaNsXVYeXlMW66GrHV9BuC4ogeLnDg9BAbmvVvfxT3hz/UFrhQRmlpZ21zh0CaN1kRS+m9DeJrilNuzw0OuADK3FIn+17cyZBoAmDqFxV4rxdRbI42LAdL4vUHoEX4ElChwOzsXKxAIH+LvVBVDcJfOhLxDupxwl2Zo6O9L+z4S9iGhxacFJyXxSujlsQeDfIoOowRDg0TNCTiXWBrNMPcDYiHb3Vkg2qujuLD53zYSY1jhypNlapjpvCgwMGFLK+tuZ4Y9ZiinqmuIiDcVDVOrViyCQ2Jj5EM+I0oz/JwBAHODgC6EIU5+T6DupMTH4c9CqtoPhKxnDL2cDDgCimH+w/ijvVA2fQ/H9i5Y3qVp/m689nZIKFh0Cgxc44nfrfbZwv3DCnUj7xVmRGVxYCFncfIbnS/XUFWpo94nUdrJc4lcF5ZyWeU659umkvQhNu5YHB58YETDpdkqWBu0SJ8=
  file: build/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: criteo-forks/mesos-consul
    tags: true
